### ISSUE TITLE
MIDI files with MT-32 resets are no longer being sent to MUNT

### ISSUE THREAD

**Issue by Mohamed00** [stuerp/foo_midi#44]
I noticed that files with MT-32 resets in them are not being sent to MUNT automatically, even though I have the location of MT-32 ROMs set. This first broke with foo_midi 2.8.3.0. Here are some example files.
[MT-32.zip](https://github.com/stuerp/foo_midi/files/15424833/MT-32.zip)

**Comment by stuerp** [comment]
I noticed that too when working on the next release. I'm pretty sure I fixed it in one of the alpha's, Have you tried those?

**Comment by Mohamed00** [comment]
Yes, just tried in 2.11.0.0-alpha7, and files with MT-32 resets are still not being sent.

**Comment by stuerp** [comment]
> Yes, just tried in 2.11.0.0-alpha7, and files with MT-32 resets are still not being sent.

I'm trying to understand what you are expecting. The example file is recognized as MT-32 and SuperMunt is used even when BASSMIDI is the selected player.

**Comment by Mohamed00** [comment]
That's what I'm not seeing. With 2.11.0.0-alpha7, as reported in the version of foo_midi reported in Preferences>Components, the files shared here, though they contain MT-32 resets, are not being sent to MUNT.

**Comment by stuerp** [comment]
> That's what I'm not seeing. With 2.11.0.0-alpha7, as reported in the version of foo_midi reported in Preferences>Components, the files shared here, though they contain MT-32 resets, are not being sent to MUNT to play without it being explicitly selected. I'm using the Secret Sauce player.

So let me see if get it: you want to use Secret Sauce in MT-32 mode when an MT-32 reset is found? Current there's only an optional override to SuperMunt.

**Comment by Mohamed00** [comment]
No, I want MIDI files with MT-32 resets in them to be sent to MUNT. This is how it worked prior to 2.8.3.0, and it broke in that version.

**Comment by Mohamed00** [comment]
Update. Works in alpha 8. Closing.
